version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::992382578667:user/aws-sam-cli-managed-prod-pipeline-reso-PipelineUser-pXvlWCL3NS4l"
permissions_provider = "AWS IAM"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::774305613815:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-EZSJN7W75ziD"
cloudformation_execution_role = "arn:aws:iam::774305613815:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-eCRr2m9csbgO"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-rhsbdcvmkmzl"
image_repository = ""
region = "us-east-1"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::992382578667:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-NXEkqDW8NInf"
cloudformation_execution_role = "arn:aws:iam::992382578667:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-5e7LmyW40wol"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-7l0mopz3wnp7"
image_repository = ""
region = "us-east-1"
