version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::273354638471:user/aws-sam-cli-managed-prod-pipeline-reso-PipelineUser-bKJGfrB532AK"
permissions_provider = "AWS IAM"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::273354638471:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-6Y0oVLInpQDM"
cloudformation_execution_role = "arn:aws:iam::273354638471:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-wK6vz2ZVs1ny"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-fn78n8cypg4e"
image_repository = "273354638471.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-yzi9gik1xkje"
region = "us-east-1"
